dashboard/urls.py
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.urls import path, include
from visualizations import views


urlpatterns = [
    path('', views.Dashboard.as_view(), name="dashboard"),
    path('visualize/', include('visualizations.urls')),
    path('admin/', admin.site.urls),
    path('visualizations/api/', include('visualizations.api.urls')),
    path('api-auth/', include('rest_framework.urls')),
]
urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


if settings.DEBUG:
    import debug_toolbar
    urlpatterns = [
        path('__debug__/', include(debug_toolbar.urls)),
        path('^tinymce/', include('tinymce.urls')),
    ] + urlpatterns

visualizations/api/urls.py
from django.urls import path, include

from rest_framework import routers

from . import viewset

router = routers.DefaultRouter()

router.register(r'district', viewset.DistrictViewSet),
router.register(r'gaunpalika', viewset.GaunpalikaViewSet),
router.register(r'data', viewset.DataViewSet)


urlpatterns = [
    path('', include(router.urls)),
    path('stfc-locations/', viewset.STFCViewSet.as_view(), name="stfc"),

]

visualizations/urls.py
from django.urls import path

from . import views

app_name = 'visualizations'

urlpatterns = [
    # path('', views.Dashboard.as_view(), name='dashboard'),
    path('housing-create', views.HousingCompletionCreate.as_view(), name="housing_create"),
    path('reconstruction-create', views.ReconstructionGrantCreate.as_view(), name="reconstruction_create"),
    path('housing-update/<int:pk>', views.HousingCompletionUpdate.as_view(), name="housing_update"),
    path('reconstruction-update/<int:pk>', views.ReconstructionGrantUpdate.as_view(), name="reconstruction-update"),
    path('recent-stories/', views.RecentStoriesView.as_view(), name="recent_stories"),
    path('recent-story-detail/<int:pk>', views.RecentStoryDetail.as_view(), name="recent_story_detail"),
    path('trainings', views.TrainingListView.as_view(), name="training"),
    path('training-detail/<int:pk>', views.TrainingDetailView.as_view(), name="training_detail"),
    path('contacts', views.ContactListView.as_view(), name="contact"),
    path('materials', views.MaterialsListView.as_view(), name="materials"),
    path('partner-detail/<int:pk>', views.ProjectStakeholdersDetailView.as_view(), name="partner_detail"),
    path('events', views.EventsListView.as_view(), name="event"),
    path('event-detail/<int:pk>', views.EventDetailView.as_view(), name="event_detail"),
    path('about', views.AboutView.as_view(), name="about"),
    path('media', views.MediaView.as_view(), name="media"),

]

visualizations/views.py
import twitter
from django.db.models import Sum, Count
from django.urls import reverse_lazy
from django.views.generic import TemplateView, CreateView, UpdateView, DetailView, ListView
from django.contrib.humanize.templatetags.humanize import intcomma

from dashboard import settings
from .models import HousingCompletion, ReconstructionGrant, Data, RecentStories, Event, Contact, Training, \
    Media, ProjectStakeholders, DispensedAmount, AboutUs, TotalAmount, Materials, OtherContact


def get_tweets():
    """
    returns twitter feed with settings as described below, contains all related twitter settings
    """
    api = twitter.Api(consumer_key=settings.CONSUMER_KEY, consumer_secret=settings.CONSUMER_SECERET,
                      access_token_key=settings.TOKEN, access_token_secret=settings.TOKEN_SECRET)
    # api= 'helo'
    # return api.GetUserTimeline(screen_name='nepalearthquake', exclude_replies=True, include_rts=False)  # includes entities
    return api.GetSearch(term="IndiaInNepalReconstruction")

    # return api


class Dashboard(TemplateView):
    """ TemplateView for Dashboard"""

    template_name = "visualizations/dashboard.html"

    def get_context_data(self, **kwargs):
        """
        :returns total houses, houses completed, houses in stage i, ii & iii, receieved tranche i, ii & iii, women
        percentage, district json path and other context values
        """
        context = super().get_context_data(**kwargs)


        all_data = {}
        data = Data.objects.all().select_related()

        total_houses_completed = 0
        total_houses_stage_i = 0
        total_houses_stage_ii = 0
        total_houses_stage_iii = 0
        total_received_tranche_i = 0
        total_received_tranche_ii = 0
        total_received_tranche_iii = 0

        sum_women_percentage = 0

        gorkha_houses_completed = 0
        gorkha_total_houses_stage_i = 0
        gorkha_total_houses_stage_ii = 0
        gorkha_total_houses_stage_iii = 0
        gorkha_total_received_tranche_i = 0
        gorkha_total_received_tranche_ii = 0
        gorkha_total_received_tranche_iii = 0

        nuwakot_houses_completed = 0
        nuwakot_total_houses_stage_i = 0
        nuwakot_total_houses_stage_ii = 0
        nuwakot_total_houses_stage_iii = 0
        nuwakot_total_received_tranche_i = 0
        nuwakot_total_received_tranche_ii = 0
        nuwakot_total_received_tranche_iii = 0

        total_houses = 0
        gorkha_total_houses = 0
        nuwakot_total_houses = 0
        for data in data:
            total_houses_completed += data.houses_completed
            total_houses_stage_i += data.houses_in_stage_i
            total_houses_stage_ii += data.houses_in_stage_ii
            total_houses_stage_iii += data.houses_in_stage_iii

            total_received_tranche_i += data.received_tranche_i
            total_received_tranche_ii += data.received_tranche_ii
            total_received_tranche_iii += data.received_tranche_iii

            total_houses += data.total_houses

            sum_women_percentage += data.women_percentage

            if data.gaunpalika.district.name == 'Gorkha':
                gorkha_total_houses += data.total_houses
                gorkha_houses_completed += data.houses_completed
                gorkha_total_houses_stage_i += data.houses_in_stage_i
                gorkha_total_houses_stage_ii += data.houses_in_stage_ii
                gorkha_total_houses_stage_iii += data.houses_in_stage_iii

                gorkha_total_received_tranche_i += data.received_tranche_i
                gorkha_total_received_tranche_ii += data.received_tranche_ii
                gorkha_total_received_tranche_iii += data.received_tranche_iii

            if data.gaunpalika.district.name == 'Nuwakot':
                nuwakot_total_houses += data.total_houses
                nuwakot_houses_completed += data.houses_completed
                nuwakot_total_houses_stage_i += data.houses_in_stage_i
                nuwakot_total_houses_stage_ii += data.houses_in_stage_ii
                nuwakot_total_houses_stage_iii += data.houses_in_stage_iii

                nuwakot_total_received_tranche_i += data.received_tranche_i
                nuwakot_total_received_tranche_ii += data.received_tranche_ii
                nuwakot_total_received_tranche_iii += data.received_tranche_iii

        dispensed_amount_obj = DispensedAmount.objects.all()[0]
        dispensed_amount = dispensed_amount_obj.amount
        total_amount_obj = TotalAmount.objects.all()[0]
        progress = (dispensed_amount * 100) / total_amount_obj.amount
        progress = int(progress)

        all_data['total_houses_completed'] = total_houses_completed
        all_data['total_houses_stage_i'] = total_houses_stage_i
        all_data['total_houses_stage_ii'] = total_houses_stage_ii
        all_data['total_houses_stage_iii'] = total_houses_stage_iii

        all_data['total_received_tranche_i'] = total_received_tranche_i
        all_data['total_received_tranche_ii'] = total_received_tranche_ii
        all_data['total_received_tranche_iii'] = total_received_tranche_iii

        all_data['ths1_percentage'] = round((total_houses_stage_i / total_houses) * 100, 2)
        all_data['ths2_percentage'] = round((total_houses_stage_ii / total_houses) * 100, 2)
        all_data['ths3_percentage'] = round((total_houses_stage_iii / total_houses) * 100, 2)

        all_data['trt1_percentage'] = round((total_received_tranche_i / total_houses) * 100, 2)
        all_data['trt2_percentage'] = round((total_received_tranche_ii / total_houses) * 100,
                                                   2)
        all_data['trt3_percentage'] = round((total_received_tranche_iii / total_houses) * 100,
                                                   2)

        all_data['gorkha_total_houses_completed'] = gorkha_houses_completed
        all_data['gorkha_total_houses'] = gorkha_total_houses

        if gorkha_total_houses is not None:
            all_data['gorkha_houses_completed_percentage'] = round((gorkha_houses_completed / gorkha_total_houses) * 100, 2)
            all_data['gorkha_ths1_percentage'] = round((gorkha_total_houses_stage_i/gorkha_total_houses)*100, 2)
            all_data['gorkha_ths2_percentage'] = round((gorkha_total_houses_stage_ii / gorkha_total_houses) * 100, 2)
            all_data['gorkha_ths3_percentage'] = round((gorkha_total_houses_stage_iii / gorkha_total_houses) * 100, 2)
            all_data['gorkha_trt1_percentage'] = round((gorkha_total_received_tranche_i / gorkha_total_houses) * 100, 2)
            all_data['gorkha_trt2_percentage'] = round((gorkha_total_received_tranche_ii / gorkha_total_houses) * 100,
                                                        2)
            all_data['gorkha_trt3_percentage'] = round((gorkha_total_received_tranche_iii / gorkha_total_houses) * 100,
                                                        2)

        all_data['gorkha_total_houses_stage_i'] = gorkha_total_houses_stage_i

        all_data['gorkha_total_houses_stage_ii'] = gorkha_total_houses_stage_ii

        all_data['gorkha_total_houses_stage_iii'] = gorkha_total_houses_stage_iii

        all_data['gorkha_total_received_tranche_i'] = gorkha_total_received_tranche_i

        all_data['gorkha_total_received_tranche_ii'] = gorkha_total_received_tranche_ii
        all_data['gorkha_total_received_tranche_iii'] = gorkha_total_received_tranche_iii

        percentage = round((total_houses_completed / total_houses) * (100), 2)
        all_data['total_houses_completed_percentage'] = percentage

        if nuwakot_total_houses is not None:
            all_data['nuwakot_houses_completed_percentage'] = round(
                (nuwakot_houses_completed / nuwakot_total_houses) * 100, 2)
            all_data['nuwakot_ths1_percentage'] = round((nuwakot_total_houses_stage_i/nuwakot_total_houses)*100, 2)
            all_data['nuwakot_ths2_percentage'] = round((nuwakot_total_houses_stage_ii / nuwakot_total_houses) * 100, 2)
            all_data['nuwakot_ths3_percentage'] = round((nuwakot_total_houses_stage_iii / nuwakot_total_houses) * 100, 2)
            all_data['nuwakot_trt1_percentage'] = round((nuwakot_total_received_tranche_i / nuwakot_total_houses) * 100, 2)
            all_data['nuwakot_trt2_percentage'] = round((nuwakot_total_received_tranche_ii / nuwakot_total_houses) * 100,
                                                        2)
            all_data['nuwakot_trt3_percentage'] = round((nuwakot_total_received_tranche_iii / nuwakot_total_houses) * 100,
                                                        2)

        all_data['nuwakot_total_houses'] = nuwakot_total_houses
        all_data['nuwakot_total_houses_completed'] = nuwakot_houses_completed

        all_data['nuwakot_total_houses_stage_i'] = nuwakot_total_houses_stage_i
        all_data['nuwakot_ths1_percentage'] = round((nuwakot_total_houses_stage_i / nuwakot_total_houses) * 100, 2)

        all_data['nuwakot_total_houses_stage_ii'] = nuwakot_total_houses_stage_ii
        all_data['nuwakot_ths2_percentage'] = round((nuwakot_total_houses_stage_ii / nuwakot_total_houses) * 100, 2)

        all_data['nuwakot_total_houses_stage_iii'] = nuwakot_total_houses_stage_iii
        all_data['nuwakot_ths3_percentage'] = round((nuwakot_total_houses_stage_iii / nuwakot_total_houses) * 100, 2)

        all_data['nuwakot_total_received_tranche_i'] = nuwakot_total_received_tranche_i
        all_data['nuwakot_trt1_percentage'] = round((nuwakot_total_received_tranche_i / nuwakot_total_houses) * 100, 2)

        all_data['nuwakot_total_received_tranche_ii'] = nuwakot_total_received_tranche_ii
        all_data['nuwakot_trt2_percentage'] = round((nuwakot_total_received_tranche_i / nuwakot_total_houses) * 100,
                                                    2)
        all_data['nuwakot_total_received_tranche_iii'] = nuwakot_total_received_tranche_iii

visualizations/templates/visualizations/about.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/custom.css' %}">
    <!------ Include the above in your HEAD tag ---------->
</head>
<body>
{% include 'visualizations/navbar.html' %}

<!-- details card section starts from here -->
<section id="about">
    <div class="container">
        <div class="row about-container">
            {% for about in about %}

                <div class="col-lg-6 content order-lg-1 order-2">
                    {{ about.content|safe }}


                </div>
                {% if about.image %}
                    <div style="background: url({{ about.image.url }}); background-size: cover;    min-height: 300px;
                            " class="col-lg-6 order-lg-2 order-1 wow fadeInRight"></div>
                {% else %}
                    <div class="col-lg-6 background order-lg-2 order-1 wow fadeInRight"></div>

                {% endif %}
            {% endfor %}

        </div>

    </div>
</section><!-- #about -->

<!-- details card section starts from here -->
<script>window.jQuery || document.write('<script src="{% static 'assets/js/vendor/jquery-1.11.2.min.js' %}"><\/script>')</script>
<script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>
</body>
</html>

visualizations/templates/visualizations/contact_list.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>

    <title></title>
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css"
          integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/custom.css' %}">
    <!------ Include the above in your HEAD tag ---------->
</head>
<body>
<!-- details card section starts from here -->
{% include 'visualizations/navbar.html' %}
<section class="details-card">
    <h2 class="title text-center">Contacts</h2>
    <br/>
    <div class="container">
        <div class="row">
            {% for contact in contacts %}

                <div class="col-md-6">
                    <div class="card-content contact-card eve text-center">
                        {% if contact.partner_name.logo %}

                            <img height="250" src="{{ contact.partner_name.logo.url }}" class="contact_img">
                        {% else %}

                            <img height="250" src="{% static 'assets/img/undp.png' %}" class="contact_img">

                        {% endif %}
                        {% if contact.partner_name %}
                            <h3>{{ contact.partner_name }}</h3>

                        {% endif %}
                        {% if contact.address %}
                            <p class="text-center w-75 m-auto">{{ contact.address }}</p>

                        {% endif %}
                        {% if contact.email %}
                            <p class="text-center w-75 m-auto"><i class="fa fa-envelope"></i> {{ contact.email }}</p>

                        {% endif %}
                        {% if contact.phone %}
                            <p class="text-center w-75 m-auto"><i class="fa fa-phone"></i> {{ contact.phone }}</p>

                        {% endif %}
                        {% if contact.website %}
                            <p class="text-center w-75 m-auto"><i class="fa fa-globe"></i> <a href="{{ contact.website }}">visit website</a></p>

                        {% endif %}
                        <br>
                    </div>
                </div>
                {% empty %}
                <h2>No Contacts</h2>
            {% endfor %}
            {% for contact in other_contacts %}

                <div class="col-md-6">
                    <div class="card-content contact-card eve text-center">
                        {% if contact.logo %}

                            <img height="250" src="{{ contact.logo.url }}" class="contact_img">


                        {% endif %}
                        {% if contact.name %}
                            <h3>{{ contact.name }}</h3>

                        {% endif %}
                        {% if contact.address %}
                            <p class="text-center w-75 m-auto">{{ contact.address }}</p>

                        {% endif %}
                       
                        {% if contact.phone %}
                            <p class="text-center w-75 m-auto"><i class="fa fa-phone"></i> {{ contact.phone }}</p>

                        {% endif %}
                       
                        <br>
                    </div>
                </div>
                
            {% endfor %}
        </div>
    </div>
</section>
<script>window.jQuery || document.write('<script src="{% static 'assets/js/vendor/jquery-1.11.2.min.js' %}"><\/script>')</script>
<script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>
<script type="text/javascript">

    $(function () {
        var selectedClass = "";
        $(".filter").click(function () {
            selectedClass = $(this).attr("data-rel");
            $("#gallery").fadeTo(100, 0.1);
            $("#gallery div").not("." + selectedClass).fadeOut().removeClass('animation');
            setTimeout(function () {
                $("." + selectedClass).fadeIn().addClass('animation');
                $("#gallery").fadeTo(300, 1);
            }, 300);
        });
    });
</script>
</body>
</html>

visualizations/templates/visualizations/event_detail.html
{% load staticfiles %}

<!DOCTYPE html>
<html>
<head>
    <title></title>
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <script src="//maxcdn.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js"></script>
    <script src="//cdnjs.cloudflare.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/custom.css' %}">
    <!------ Include the above in your HEAD tag ---------->
</head>
<body>
<!-- details card section starts from here -->
{% include 'visualizations/navbar.html' %}

<section class="details-card">
    <div class="container">
        <div class="row">
            <div class="col-md-12">
                <div class="card-content text-left">
                    <div class="card-img">
                        {% if event.image %}
                            <img src="{{ event.image.url }}" alt="" class="event-img">

                        {% endif %}
                    </div>
                    <div class="card-desc">
                        <h3>{{ event.title }}</h3>
                        <p>{{ event.description }}</p>
                        <p class="time"> {{ event.event_date }}</p>

                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
</body>
</html>

visualizations/templates/visualizations/event_list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
  <title></title>
<link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
<link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

<link rel="stylesheet" type="text/css" href="{% static 'assets/css/custom.css' %}">
<!------ Include the above in your HEAD tag ---------->
</head>
<body>
<!-- details card section starts from here -->
{% include 'visualizations/navbar.html' %}

<section class="details-card">
    <h2 class="title text-center margin-top-large">Events</h2>

    <div class="container">
        <div class="row">
            {% for event in events %}

            <div class="col-md-12">
                <div class="card-content eve">
                  <div class="row">

                    <div class="col-md-4 card-img">
                        {% if event.image %}
                            <img src="{{ event.image.url }}" alt="">

                            {% else %}
                                 <img src="https://placeimg.com/380/230/nature" alt="">
                        {% endif %}
                       <!--  <span><h4>heading</h4></span> -->
                    </div>
                    <div class="col-md-8 card-desc text-left">

                             <h3>{{ event.title }} </h3>                            <p class="time"> {{ event.event_date }}</p>

                            <p>{{ event.description|truncatechars:250 }} <a href="{% url 'visualizations:event_detail' event.pk %}">Read More</a></p>



                    </div>

                  </div>
                </div>
            </div>
                {% empty %}
                <p>No Events</p>
                      {% endfor %}

        </div>
    </div>

</section>
<!-- details card section starts from here -->
<script>window.jQuery || document.write('<script src="{% static 'assets/js/vendor/jquery-1.11.2.min.js' %}"><\/script>')</script>
<script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>

</body>
</html>

visualizations/templates/visualizations/navbar.html
<div class="sub-nav">

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'dashboard' %}"><i class="fas fa-home"></i><span class="sr-only">(current)</span></a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'visualizations:about' %}">About</a>
                </li>
                <li class="nav-item">
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'visualizations:media' %}">Media</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'visualizations:materials' %}">Materials</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'visualizations:event' %}">Events</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'visualizations:training' %}">Training</a>
                </li>

                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button"
                       data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
                        Partners
                    </a>
                    <div class="dropdown-menu" aria-labelledby="navbarDropdown">
                        {% for partner in partners %}
                            <a class="dropdown-item"
                               href="{% url 'visualizations:partner_detail' partner.pk %}">{{ partner.name }}</a>

                        {% endfor %}


                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'visualizations:contact' %}">Contact</a>
                </li>

            </ul>


        </div>
    </nav>
</div>

visualizations/templates/visualizations/story_detail.html
{% load static %}
{% load staticfiles %}
{% load twitter_tags %}
{% load humanize %}
<!doctype html>
<!--[if lt IE 7]>      <html class="no-js lt-ie9 lt-ie8 lt-ie7" lang=""> <![endif]-->
<!--[if IE 7]>         <html class="no-js lt-ie9 lt-ie8" lang=""> <![endif]-->
<!--[if IE 8]>         <html class="no-js lt-ie9" lang=""> <![endif]-->
<!--[if gt IE 8]><!-->
<html class="no-js" lang="en"> <!--<![endif]-->
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
    <title></title>
    <meta name="description" content="">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link rel="apple-touch-icon" href="apple-touch-icon.png">
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <script src="{% static 'assets/js/vendor/modernizr-2.8.3-respond-1.4.2.min.js' %}"></script>
            <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <style>

        #map {
            width: 100%;
            height: 100%;
        }
        .legend{
            background: white;
            padding: 5px;
        }
        .info{
            background: white;
            padding:5px;
        }
    </style>
</head>
{% include 'visualizations/navbar.html' %}
<body class="bg-gray ">
<!--[if lt IE 8]>
            <p class="browserupgrade">You are using an <strong>outdated</strong> browser. Please <a href="http://browsehappy.com/">upgrade your browser</a> to improve your experience.</p>
        <![endif]-->

<div class="bg-gray module-padding">
    <div class="container">
        <div class="module-story">
            <div class="story-header">
                <a href="{% url 'visualizations:recent_stories' %}" title="" class="float-left">All Stories</a>
            </div>
            <div class="story-section padding-top">
                
                {% if story.banner_image %}
                <img src="{{story.banner_image.url}}" alt="" class="img-responsive">
   
                {% endif %}
                    
                <div class="row margin-top">
                    <div class="col-md-12">
                        <div class="story-item">
                            <img src="{{story.thumbnail.url}}" alt="" width="100" height="100">
                            <div class="user-info">
                                <h6>{{ story.title }}</h6>
                                <span>{{ story.description }}</span>
                            </div>
                            <p>
                                {{ story.content| safe}}
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>


<script>window.jQuery || document.write('<script src="{% static 'assets/js/vendor/jquery-1.11.2.min.js' %}"><\/script>')</script>
<script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>
<script src="{% static 'assets/js/plugins.js' %}"></script>
</body>
</html>

visualizations/templates/visualizations/training_list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <link rel="stylesheet" href="{% static 'assets/css/style.css' %}">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.2.0/css/all.css" integrity="sha384-hWVjflwFxL6sNzntih27bfxkr27PmbbK/iSvJ+a4+0owXq79v+lsFkW54bOGbiDQ" crossorigin="anonymous">

    <link rel="stylesheet" type="text/css" href="{% static 'assets/css/custom.css' %}">
    <!------ Include the above in your HEAD tag ---------->
</head>
<body>
<!-- details card section starts from here -->
{% include 'visualizations/navbar.html' %}

<section class="details-card">
    <div class="container">
        <h2 class="title text-center margin-top-large">Trainings</h2>

        <div class="row">
            {% for training in trainings %}


                <div class="col-md-4">
                    <div class="card-content">
                        <div class="card-img">
                            {% if training.image %}
                                <img src="{{ training.image.url }}" alt="">

                             {% else %}
                                <img src="https://placeimg.com/380/230/nature" alt="">

                            {% endif %}
                        </div>
                        <div class="card-desc">
                            <h3>{{ training.title }}</h3>
                            <p>{{ training.description|truncatechars:150  }} <a href="{% url 'visualizations:training_detail' training.pk %}">Read More</a></p>
                        </div>
                    </div>
                </div>

                {% empty %}
                <p>No Trainings</p>
            {% endfor %}


    </div>
    </div>
</section>
<!-- details card section starts from here -->
<script>window.jQuery || document.write('<script src="{% static 'assets/js/vendor/jquery-1.11.2.min.js' %}"><\/script>')</script>
<script src="{% static 'assets/js/vendor/popper.min.js' %}"></script>
<script src="{% static 'assets/js/vendor/bootstrap.min.js' %}"></script>

</body>
</html>